'''

                            Online Python Compiler.
                Code, Compile, Run and Debug python program online.
Write your code in this editor and press "Run" button to execute it.

'''
form9 = ['户数 Number of Households',
                    '男性人口 Male Population',
                    '女性人口 Female Population',
                    '总人口 Total Population',
                    '流动人口/暂住人口 Migratory/Temporary Population',
                    '出生人数 Number of Births',
                    '自然出生率 Birth Rate (‰)',
                    '死亡人数 Number of Deaths',
                    '死亡率 Death Rate (‰)',
                    '自然增长率 Natural Population Growth Rate (‰)',
                    '迁入 (户数) Migration In (number of households)',
                    '迁出 (户数) Migration Out (number of households)',
                    '知识青年迁入 Educated Youth - Migration In',
                    '知识青年迁出 Educated Youth - Migration Out',
                    '农转非 (人数) Agricultural to Non-Agricultural Hukou / Change of Residency Status (number of people)',
                    '农转非 (户数) Agricultural to Non-Agricultural Hukou / Change of Residency Status (number of households)']
form10 = ['入伍 Military Enlistment',
                     '村民纠纷 Number of Civil Mediations',
                     '刑事案件 Number of Reported Crimes',
                     '共产党员 - 男 CCP Membership - Male',
                     '共产党员 - 女 CCP Membership - Female',
                     '共产党员 - 总 CCP Membership - Total',
                     '共产党员 - 少数民族 CCP Membership - Ethnic Minorities',
                     '新党员 - 男 New CCP Membership - Male',
                     '新党员 - 女 New CCP Membership - Female',
                     '新党员 - 总 New CCP Membership - Total',
                     '新党员 - 少数民族 New CCP Membership - Ethnic Minorities',
                     '阶级成分 - 地主 (户数) Class Status - Landlord (number of households)',
                     '阶级成分 - 富农 (户数) Class Status - Rich Peasant (number of households)',
                     '阶级成分 - 中农 (户数) Class Status - Middle Peasant (number of households)',
                     '阶级成分 - 贫下中农 (户数) Class Status - Poor and Lower Middle Peasant (number of households)']
form11 = ['总产值 (万元) Gross Output Value (10K yuan)',
                     '集体经济收入 (元) Collective Economic Income (yuan)',
                     '集体经济收入 (万元) Collective Economic Income (10K yuan)',
                     '耕地面积 (亩) Cultivated Area (mu)',
                     '耕地面积 (公顷) Cultivated Area (hectares)',
                     '粮食总产量 (万斤) Total Grain Output (10K pounds)',
                     '粮食总产量 (吨) Total Grain Output (tons)',
                     '粮食总产量 (万吨) Total Grain Output (10K tons)',
                     '用电量 - 每人 (度) Village Power Consumption - per person (kilowatt-hours)',
                     '用电量 - 每户 (度) Village Power Consumption - per household (kilowatt-hours)',
                     '用电量 - 全村 (度) Village Power Consumption - Village (kilowatt-hours)',
                     '电价 (元每度) Electricity Price - General (yuan per kilowatt-hour)',
                     '电价 - 生活用电 (元每度) Electricity Price - Domestic (yuan per kilowatt-hour)',
                     '电价 - 农业用电 (元每度) Electricity Price - Agricultural (yuan per kilowatt-hour)',
                     '电价 - 工业用电 (元每度) Electricity Price - Industrial (yuan per kilowatt-hour)',
                     '水价 (元每立方米) Water Price (yuan per cubic meter)',
                     '人均收入 (元) Per Capita Income (yuan)',
                     '人均居住面积 (平方米) Per Capita Living Space (square meters)']
form12 = ['计划生育参与率 Family Planning Program Participation Rate (%)',
                     '领取独生子女证 (人数) Certified Commitment to One Child Policy (number of people)',
                     '育龄妇女人口 Number of Women of Childbearing Age',
                     '生育率 Total Fertility Rate (‰)',
                     '男性结扎 Vasectomies',
                     '女性结扎 Tubal Ligations',
                     '上环 Use of Intrauterine Device (IUD)',
                     '绝育手术 Sterilization Surgeries']
form13 = ['在校生 - 小学 Students in School - Elementary School',
                     '在校生 - 初中 Students in School - Junior High School',
                     '在校生 - 高中 Students in School - High School',
                     '新入学生 - 大学 Initial Student Enrollment - College/University',
                     '老师- 小学 Teachers - Elementary School',
                     '老师- 初中 Teachers - Junior High School',
                     '老师- 高中 Teachers - High School',
                     '受教育程度 - 文盲 Illiterate',
                     '受教育程度 - 小学 Highest Level of Education - Elementary School',
                     '受教育程度 - 初中 Highest Level of Education - Junior High School',
                     '受教育程度 - 中专高中 Highest Level of Education - High School',
                     '受教育程度 - 大专以上 Highest Level of Education - College/University or Higher']
form14 = ['视力残疾 Blindness',
                     '听力语言残疾 Hearing and Speech Disabilities',
                     '肢体残疾 Amputation and/or Paralysis',
                     '精神残疾 Mental Disabilities',
                     '智力残疾 Intellectual Disabilities',
                     '残疾人总数 Total Disabled Population']
for cate in form14:
    val = cate+"|"+cate
    print(val)
