var dCate9 = [
  "人口 Population^男性人口 Male Population^^^",
  "人口 Population^女性人口 Female Population^^^",
  "人口 Population^总人口 Total Population^^^",
  "迁入 Migration In^^人数 number of people^^",
  "迁入 Migration In^^户数 number of households^^",
  "迁入 Migration In^^知识青年 Educated Youth^^",
  "迁出 Migration Out^^人数 number of people^^",
  "迁出 Migration Out^^户数 number of households^^",
  "迁出 Migration Out^^知识青年 Educated Youth^^",
  "农转非 Agricultural to Non-Agricultural Hukou / Change of Residency Status^^^人数 number of people^",
  "农转非 Agricultural to Non-Agricultural Hukou / Change of Residency Status^^^ 户数 number of households^",
  "残疾人数 Disabled Population^^^^视力残疾 Blindness",
  "残疾人数 Disabled Population^^^^听力语言残疾 Hearing and Speech Disabilities",
  "残疾人数 Disabled Population^^^^肢体残疾 Amputation and/or Paralysis",
  "残疾人数 Disabled Population^^^^精神残疾 Mental Disabilities",
  "残疾人数 Disabled Population^^^^智力残疾 Intellectual Disabilities",
  "残疾人数 Disabled Population^^^^残疾人总数 Total Disabled Population",
  "户数 Number of Households^^^^", "出生人数 Number of Births^^^^",
  "自然出生率 Birth Rate (‰)^^^^", "自然出生率 Birth Rate (%)^^^^",
  "死亡人数 Number of Deaths^^^^", "死亡率 Death Rate (‰)^^^^",
  "死亡率 Death Rate (%)^^^^", "自然增长率 Natural Population Growth Rate (‰)^^^^",
  "自然增长率 Natural Population Growth Rate (%)^^^^",
  "流动人口/暂住人口 Migratory/Temporary Population^^^^"
];

var dCate10 = [
  "新党员 New CCP Membership^男 Male^^^",
  "新党员 New CCP Membership^女 Female^^^",
  "新党员 New CCP Membership^总 Total^^^",
  "新党员 New CCP Membership^少数民族 Ethnic Minorities^^^",
  "共产党员 CCP Membership^男 Male^^^",
  "共产党员 CCP Membership^女 Female^^^",
  "共产党员 CCP Membership^总 Total^^^",
  "共产党员 CCP Membership^少数民族 Ethnic Minorities^^^",
  "阶级成分 Class Status^^地主 Landlord^^",
  "阶级成分 Class Status^^富农 Rich Peasant^^",
  "阶级成分 Class Status^^中农 Middle Peasant^^",
  "阶级成分 Class Status^^贫下中农 Poor and Lower Middle Peasant^^",
  "入伍 Military Enlistment^^^^",
  "村民纠纷 Number of Civil Mediations^^^^",
  "刑事案件 Number of Reported Crimes^^^^"
];

var dCate11 = [
  "总产值 Gross Output Value^总 Total^^^",
  "总产值 Gross Output Value^第一产业 Raw Materials^^^",
  "总产值 Gross Output Value^种植业 Agriculture^^^",
  "总产值 Gross Output Value^林业 Forestry^^^",
  "总产值 Gross Output Value^牧业 Animal Husbandry^^^",
  "总产值 Gross Output Value^副业 Miscellaneous^^^",
  "总产值 Gross Output Value^渔业 Fishery^^^",
  "总产值 Gross Output Value^第二产业 Secondary Industry^^^",
  "总产值 Gross Output Value^第三产业 Service^^^",
  "集体经济收入 Collective Economic Income^总 Total^^^",
  "集体经济收入 Collective Economic Income^第一产业 Raw Materials^^^",
  "集体经济收入 Collective Economic Income^种植业 Agriculture^^^",
  "集体经济收入 Collective Economic Income^林业 Forestry^^^",
  "集体经济收入 Collective Economic Income^牧业 Animal Husbandry^^^",
  "集体经济收入 Collective Economic Income^副业 Miscellaneous^^^",
  "集体经济收入 Collective Economic Income^渔业 Fishery^^^",
  "集体经济收入 Collective EconomicIncome^第二产业 Secondary Industry^^^",
  "集体经济收入 Collective Economic Income^第三产业 Service^^^",
  "用电量 Electricity Consumption^^General^^",
  "用电量 Electricity Consumption^^农业Agricultural^^",
  "用电量 Electricity Consumption^^工业 Industrial^^",
  "用电量 Electricity Consumption^^生活 Household^^",
  "用电量 Electricity Consumption^^商业 Commercial^^",
  "电价 Electricity Price^^General^^",
  "电价 Electricity Price^^农业 Agricultural^^",
  "电价 Electricity Price^^工业 Industrial^^",
  "电价 Electricity Price^^生活 Household^^",
  "电价 Electricity Price^^商业 Commercial^^",
  "用水量 Water Consumption^^General^^",
  "用水量 Water Consumption^^农业 Agricultural^^",
  "用水量 Water Consumption^^工业 Industrial^^",
  "用水量 Water Consumption^^生活 Household^^",
  "用水量 Water Consumption^^商业 Commercial^^",
  "水价 Water Price^^General^^",
  "水价 Water Price^^农业 Agricultural^^",
  "水价 Water Price^^工业 Industrial^^",
  "水价 Water Price^^生活 Household^^",
  "水价 Water Price^^商业 Commercial^^",
  "耕地面积 Cultivated Area^^^^",
  "粮食总产量 Total Grain Output^^^^",
  "人均收入 Per Capita Income^^^^",
  "人均居住面积 Per Capita Living Space^^^^"
];

var dCate12 = [
  "育龄妇女人口 Number of Women of Childbearing Age^^^^",
  "领取独生子女证 (人数) Certified Commitment to One Child Policy (number of people)^^^^",
  "节育率 (%) Rate of Contraception (%)^^^^",
  "计划生育率 (%) Planned Birth Rate (%)^^^^",
  "上环 Use of Intrauterine Device (IUD)^^^^",
  "绝育手术 Sterilization Surgeries^^^^",
  "男性结扎 Vasectomies^^^^",
  "女性结扎 Tubal Ligations^^^^",
  "结扎总数 Total Number of Vasectomies and Tubal Ligations^^^^",
  "人工流产 Abortions^^^^",
  "引产 Late-term Abortions^^^^"
];

var dCate13 = ["在校生 Students in School^小学 Elementary School^^^",
  "在校生 Students in School^初中 Junior High School^^^",
  "在校生 Students in School^高中 High School^^^",
  "老师 Teachers^小学 Elementary School^^^",
  "老师 Teachers^初中 Junior High School^^^",
  "老师 Teachers^高中 High School^^^",
  "受教育程度 Highest Level of Education^^文盲 Illiterate^^",
  "受教育程度 Highest Level of Education^^小学 Elementary School^^",
  "受教育程度 Highest Level of Education^^初中 Junior High School^^",
  "受教育程度 Highest Level of Education^^中专高中 High School^^",
  "受教育程度 Highest Level of Education^^大专以上 College/University or Higher^^",
  "新入学生 - 大学 Initial Student Enrollment - College/University^^^^"
];
